configMapGenerator:
  - name: openhim-config-importer-configmap
    files:
      - ./volume/openhim-import.json
      - ./volume/openhimConfig.js
resources:
  - ./core-openhim-config-importer-job.yaml
